apiVersion: v1
kind: Service
metadata:
    name: kubeservice
spec:
    selector:
        app: ecommerce-app
    ports:
        - port: 80
          targetPort: 8080
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ecommerce-app
spec:
    replicas: 5
    selector:
        matchLabels:
            app: ecommerce-app
    template:
        metadata:
            labels:
                app: ecommerce-app
        spec:
            containers:
                - name: ecommerce-app
                  image: ernestojr/ecommerce:1.0.0
                  ports:
                      - containerPort: 8080
                  env:
                      - name: MONGO_URL
                        value: mongodb+srv://developer:QmSQ489uyGo2WqJk@cluster0.beaz15s.mongodb.net/ecommerce-docker
                  imagePullPolicy: Always
